# Usa una imagen oficial de Python ligera
FROM python:3.10-slim

# Define la carpeta de trabajo dentro del contenedor
WORKDIR /app

# Copia la lista de librerías e instálalas
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo el código del backend hacia el contenedor
COPY . .

# Expone el puerto 3000 que mapeamos en el docker-compose
EXPOSE 3000

# Comando para arrancar FastAPI usando Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3000"]